### ISSUE TITLE
Unable to open link to commit from event

### ISSUE THREAD

**Issue by Mikoj** [thedillonb/CodeBucket#12]
On event page click commit and get this ![](http://i.imgur.com/yJFQ2et.jpg)

**Comment by thedillonb** [comment]
Hey @Mikoj, I'm unable to reproduce this. Walk me through your process:

1. You go to the "Events" view
2. You click on a commit (A assume you click on the hash?)
3. You receive this error message?

**Comment by Mikoj** [comment]
exactly on event view click commit hash and receive this error.

**Comment by thedillonb** [comment]
Cleaning up this ticket as Mikoj has already submitted a PR, and merged, a fix for this.
