### ISSUE TITLE
Cannot activate previous purchase

### ISSUE THREAD

**Issue by rohan-deshpande** [thedillonb/CodeBucket#20]
Possibly this is related to my app updating and me not being on the latest version of iOS (I'm on `9.3.2`) but I cannot activate my previous purchase. I get to the **Activating...** dialog and it just hangs. 

Will see if updating iOS fixes the issue.

**Edit** Nope that didn't fix it, updated to the latest version of iOS; `v9.3.4` and the issue is still there.

**Comment by thedillonb** [comment]
Interesting. I'll take a look at that. As a quick work around you should be able to "purchase" it again without actually purchasing. If you choose to "Go Pro" it'll ask you if you're sure you want to purchase the item, if you say yes, it will say "You've already purchased this item, do you want to download it again?" And just say yes.

Because the Pro edition is a non-consumable item, if you bought it once from Apple you'll never pay for it again. There's probably something funky with the restore logic which is causing this issue.

If you're weary of purchasing it again, try closing the app out. It may just be a UI component that is stuck loading and not really the restore functionaility.

**Comment by rohan-deshpande** [comment]
No that didn't really work. It's still asking me to purchase the pro version. 

Did you add this pro version recently? I don't remember the app ever being free, I am pretty sure I had to pay for it right away. 

I was browsing all my repos fine until the latest update. All my repos on Bitbucket are private, public stuff goes on GitHub.

I mean, $2.99 is nothing, it's just the principle of the thing.

**Comment by thedillonb** [comment]
Interesting. The Pro version is very recent. About a year ago the app was paid but I had made it free while I rewrote it and restructured it. I had put in code to make sure people whom had downloaded it before Pro came out would get Pro for free. I strongly believe that people who paid for it, or downloaded it while free, should not be made to pay again. 

The fact it's asking you to pay again is not correct. Let me see if I can find a solution to this. I don't think you should pay for it if you've already had the app before "Pro" became a thing.

**Comment by thedillonb** [comment]
@rohan-deshpande I just submitted a version of the app that will hopefully fix the restore functionality. Give that a try. If that does **not** work let me know. I'll make the in-app purchase free for a couple of days so you can grab it and not have to worry about it in the future. I thought maybe a "promo" code would work as a temporary hack but it looks like Apple's promo codes are only good for giving away the app, not in-app purchases. Oh well.

**Comment by rohan-deshpande** [comment]
Hey thanks, doesn't seem like that version has been approved yet as the app isn't showing up as needing an update right now. I'll wait until it does to check and see. 

I'm actually surprised I'm the only one experiencing this, surely this issue would be the same for everyone who bought the app prior to the change or am I just special?

That's kind of annoying re: in app purchases. Definitely a way to circumvent family sharing of apps as well I guess.

**Comment by thedillonb** [comment]
New version has just been released that should resolve the "Restore Purchases" issue. Let me know if that works or not and I'll cook up something else if it doesn't.

**Comment by rohan-deshpande** [comment]
Hey, thanks for this. Got the update, sadly it didn't work, the infinite spinner is gone but it just disappears and takes me back to the upgrade page as if nothing has happened.

**Comment by thedillonb** [comment]
@rohan-deshpande, I've made the Pro version free for a day, starting now so you can pick it up. I'm still confused why restore is not working but this will allow you to grab the upgrade which you had at one point free of charge. ;)

**Comment by rohan-deshpande** [comment]
Okay, doing it now it's still saying the price is $2.99 lol it's okay at this point I think I can safely buy again even if it happens! Thanks for trying even if it doesn't work 👍

**Comment by thedillonb** [comment]
It might take a while for that change to propagate through iTunes for all regions.

**Comment by rohan-deshpande** [comment]
It's fine, I already did it! haha

**Comment by thedillonb** [comment]
Ah! Well, regardless, I hope you enjoy! Let me know if there are any other problems you run into.
