### ISSUE TITLE
Cannot log in - 403

### ISSUE THREAD

**Issue by DominikPalo** [thedillonb/CodeBucket#21]
I'm trying to log in to iOS app (on iPhone 6), but every attempt fails with an error 403 (email and password are 100% correct).
![img_1203](https://cloud.githubusercontent.com/assets/1623257/20399934/20e0c9d4-acf3-11e6-86a8-ce9bbd1e01fa.PNG)

**Comment by thedillonb** [comment]
@DominikPalo, are you still seeing this issue? I just gave it a try and it looks like it worked. This looks like a regression on Bitbucket's side as their OAuth portal is notoriously buggy.

**Comment by DominikPalo** [comment]
Thanks, now it's working again
