### ISSUE TITLE
Don't presume credentials problem when bitbucket.org can't be reached.

### ISSUE THREAD

**Issue by pbx** [thedillonb/CodeBucket#3]
Bitbucket is down this morning, but the app (after trying a long while) instead suggested that my password might be incorrect.  No need to mislead the user this way -- if the server times out, say that.  Or use http://status.bitbucket.org/ info for something more definitive.

**Comment by thedillonb** [comment]
This has since been resolved as we now rely on BitBucket's OAuth for authentication which eliminates the need for that previous error message.
